### ISSUE TITLE
Data Mistake - 10 Aug

### ISSUE THREAD

**Issue by rosenbergd** [JayWelsh/coronamap#2]
Hi again, I've noticed another minor mistake in the data:
![image](https://user-images.githubusercontent.com/5484305/89879035-9e0cd180-dbc2-11ea-957b-a25525ce3fe5.png)

Thanks for fixing the previous one so quickly

**Comment by JayWelsh** [comment]
Hi @rosenbergd ,

I have put a fix in place to avoid this bug occurring again (basically total case data for the 10th exists but death + recovery data does not exist in that data source yet), so, for now, it will just show up until the 9th until that data becomes available.

However, I will put a fix in place to use data source which gets updated more quickly, when I get a chance, for the deaths + recoveries so that there is less of a lag on the active cases chart going forward.

Thanks a lot for your help! I really appreciate it! <3

**Comment by JayWelsh** [comment]
Fixed by https://github.com/JayWelsh/coronamap/commit/d25bcc09183fa258552e5a6938f2af7a3cb4f4b5
